#!/bin/bash

# jfunctions - general bash functions for use in Joomla bash scripts
# Supports Joomla versions 2.5 - 3.x
#
# Copyright 2014 Rene Kreijveld - email@renekreijveld.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Version history
# 3.0 Initial version
# 3.1 Code rewrite
# 3.2 Modification of all echo -e statements and remove backticks
# 3.3 Update to support Joomla 3.5
# 3.4 Dropped support for Joomla versions lower than 2.5
# 3.5 Added support for Joomla 3.8 and up

# Define general variables
version=3.5

# Check if configuration.php exists.
if [ ! -e ./configuration.php ]
then
    echo ""
    echo "File configuration.php not found. Are you at the root of the site?"
    echo ""
    exit 1
fi

# Grab information from Joomla 2.5/3.x configuration.
sitename=$(grep '$sitename =' ./configuration.php | cut -d \' -f 2 | sed 's/ /_/g')
sitenameclean=$(grep '$sitename =' ./configuration.php | cut -d \' -f 2)
database=$(grep '$db =' ./configuration.php | cut -d \' -f 2)
dbuser=$(grep '$user =' ./configuration.php | cut -d \' -f 2)
password=$(grep '$password =' ./configuration.php | cut -d \' -f 2)
host=$(grep '$host =' ./configuration.php | cut -d \' -f 2)
prefix=$(grep '$dbprefix =' ./configuration.php | cut -d \' -f 2)
if [ -e ./libraries/src/Version.php ]
then
    versr=$(grep 'RELEASE =' ./libraries/src/Version.php | cut -d \' -f 2)
    versd=$(grep 'DEV_LEVEL =' ./libraries/src/Version.php | cut -d \' -f 2)
    verss=$(grep 'DEV_STATUS =' ./libraries/src/Version.php | cut -d \' -f 2)
else
    versr=$(grep 'RELEASE =' ./libraries/cms/version/version.php | cut -d \' -f 2)
    versd=$(grep 'DEV_LEVEL =' ./libraries/cms/version/version.php | cut -d \' -f 2)
    verss=$(grep 'DEV_STATUS =' ./libraries/cms/version/version.php | cut -d \' -f 2)
fi