#!/bin/sh

# jdbdump -- Dump a Joomla database to sql file.
#
# This scripts supports Joomla versions 2.5 - 3.x
#
# Copyright 2014 - 2016 Rene Kreijveld - r.kreijveld@dsd.nu
#
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file jfunctions. This has to be installed in the same directory as this script.
#
# Version history
# 3.0 Initial version
# 3.1 Code rewrite
# 3.2 Modification of all echo -e statements
# 3.3 Added test if jfunctions exists
# 3.4 Removed socket option for macOS

# general variables
mypath=$(cd $(dirname ${0}); pwd -P)
myname=$(basename ${0})

# include general functions
if [ ! -e ${mypath}/jfunctions ]
then
	echo ""
	echo "Cannot continue: script jfunctions not found."
	echo ""
	exit 1
else
	. ${mypath}/jfunctions
fi

# version
version=3.4

# display usage information
usage() {
	echo ""
	echo "${myname} version ${version}, written by Rene Kreijveld."
	echo ""
	echo "Usage: ${myname} [-d] [-h]"
	echo ""
	echo "-d Add a date-time-stamp to the database dump filename."
	echo "-h Help. Display this info."
	echo ""
	exit 0
}

# process the arguments
while getopts dh opt
do
	case "${opt}" in
		d)
			showdate="yes"
			;;
		h)
			usage
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires an argument." >&2
			exit 1
			;;
	esac
done

if [ "${showdate}" == "yes" ]
then
	now=$(date +"%Y%m%d-%H%M%S")
else
	now=""
fi

echo ""
echo "${myname} version ${version}, written by Rene Kreijveld."
echo ""
echo "This is a Joomla! ${versr}.${versd} site. Starting database dump..."

# dump the database to a .sql file
if mysqldump --skip-opt --add-drop-table --add-locks --create-options --disable-keys --lock-tables --quick --set-charset --host=${host} --user=${dbuser} --password=${password} ${database} > ${database}${now}.sql 2>/dev/null
then
	echo "${database}${now}.sql created."
	ls -l ${database}${now}.sql
	exit 0
else
	echo "Error creating database dump."
	exit 1
fi