#!/bin/sh

# jdbimp -- Import a sql file into a Joomla database.
# Supports Joomla versions 1.0 - 3.3
#
# Copyright 2014 Rene Kreijveld - email@renekreijveld.nl
#
# This program is free software; you may redistribute it and/or modify it.
#
# Warning! This script needs the file joomlafunctions. This has to be installed in the same directory as this script.
#
# Version history
# 1.0 Initial version
# 2.0 Major updates
# 3.0 Code rewrite
# 3.1 Modification of all echo -e statements
# 3.2 Added test if jfunctions exists
# 3.3 Removed socket option for macOS

# General variables
version=3.3

# Determine path of script
mypath=$(cd $(dirname ${0}); pwd -P)
myname=$(basename ${0})

# include general functions
if [ ! -e ${mypath}/jfunctions ]
then
	echo ""
	echo "Cannot continue: script jfunctions not found."
	echo ""
	exit 1
else
	. ${mypath}/jfunctions
fi

echo ""
echo "${myname} version ${version}, written by Rene Kreijveld."
echo ""
echo "This is a Joomla! ${versr}.${versd} site. Starting database import..."

# Check if database dump exists.
if [ ! -e $database.sql ]
then
	echo "Database dump $database.sql not found!"
	exit 1
fi

# Import the database from a .sql file
if mysql --host=$host --user=$dbuser --password=$password $database < $database.sql 2>/dev/null
then
	echo "$database.sql imported."
	exit 0
else
	echo "Error importing database dump."
	exit 1
fi